apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    ssd.admissionreview.accountname: dev
    ssd.admissionreview.appname: cve3094 # Your app name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      ssd.admissionreview.accountname: dev
      ssd.admissionreview.appname: cve3094 # Your app name
  template:
    metadata:
      labels:
        app: nginx
        ssd.admissionreview.accountname: dev
        ssd.admissionreview.appname: cve3094 # Your app name 
    spec:
      containers:
      - name: nginx
        image: debian:experimental-20240311@sha256:16cc2b09c44d991d36f63153f13a7c98fb7da6bd2ba9d7cc0f48baacb7484970
        ports:
        - containerPort: 80
